<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Netsphere</RootNamespace>
    <AssemblyName>Game</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BlubLib"><HintPath>..\..\libs\BlubLib7\BlubLib.dll</HintPath></Reference>
    <Reference Include="BlubLib.DotNetty"><HintPath>..\..\libs\BlubLib7\BlubLib.DotNetty.dll</HintPath></Reference>
    <Reference Include="BlubLib.DotNetty.SimpleRmi"><HintPath>..\..\libs\BlubLib7\BlubLib.DotNetty.SimpleRmi.dll</HintPath></Reference>
    <Reference Include="BlubLib.Serialization"><HintPath>..\..\libs\BlubLib7\BlubLib.Serialization.dll</HintPath></Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.2" />
    <PackageReference Include="Dapper.FastCrud" Version="2.4.0" />
    <PackageReference Include="DotNetty.Buffers" Version="0.6.0" />
    <PackageReference Include="DotNetty.Common" Version="0.6.0" />
    <PackageReference Include="DotNetty.Transport" Version="0.6.0" />
    <PackageReference Include="Expressmapper" Version="1.8.1" />
    <PackageReference Include="Hjson" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
    <PackageReference Include="MySqlConnector" Version="2.3.6" />
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
    <PackageReference Include="NLog" Version="4.7.15" />
    <PackageReference Include="Stateless" Version="2.5.80" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.103" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auth.ServiceModel\Auth.ServiceModel.csproj" />
    <ProjectReference Include="..\Netsphere.Database\Netsphere.Database.csproj" />
    <ProjectReference Include="..\Netsphere.Network\Netsphere.Network.csproj" />
    <ProjectReference Include="..\Netsphere\Netsphere.csproj" />
    <ProjectReference Include="..\ProudNet\ProudNet.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="game.hjson" Condition="Exists('game.hjson')"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></None>
    <None Update="NLog.config"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></None>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Network\PacketFirewallRule.cs" />
  </ItemGroup>
</Project>
