<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Netsphere.Database</RootNamespace>
    <AssemblyName>Netsphere.Database</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.2" />
    <PackageReference Include="Dapper.FastCrud" Version="2.4.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net48'">
    <Reference Include="System.ComponentModel.DataAnnotations" />
  </ItemGroup>
</Project>
